### ISSUE TITLE
T_Glb_TerrWater_Circle256_01 needs collision removed

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#687] opened 2024-09-16 03:52 UTC
T_Glb_TerrWater_Circle256_01 still has collision, which interferes with a quest in Anvil that requires the player to recover an item from underneath the water plane.

The mesh is TR\x\TR_water_Circle256_DG.nif

**Comment by antonisauren** [comment] 2024-10-16 02:30
I can;t replicate the issue. Mesh is structured the same as other water planes. Player clips through and can pick up items below it. At least on MGEXE setup.

**Comment by Assumeru** [comment] 2024-10-16 12:12
Broken in OpenMW 0.48, but works in 0.49.

Of course its CS marker is visible in _actual_ vanilla.

**Comment by antonisauren** [comment] 2024-10-16 15:08
On MGEXE they were not rendered or I'm blind.

**Comment by trav5555** [comment] 2024-11-13 21:12
I found a workaround, which makes me wonder if this issue is an asset issue or OpenMW issue. I can post it on openmw gitlab as soon as anybody else confirms their issue reproduced and then fixed with this workaround.

The issue occurs for me in the exterior cells (not interior!) when you have an [object paging](https://openmw.readthedocs.io/en/latest/reference/modding/settings/terrain.html#object-paging) enabled.

(in the launcher options it's under Settings->Visual->Terrain->Active Grid Object Paging
or in your user settings.cfg file:
```
[Terrain]
distant terrain = true
object paging = true
object paging active grid = true
```
)

When I disable `object paging active grid`, I can pickup items from underneath the water. And items aren't placed on top of it.

See PT Discord: https://discord.com/channels/261789910594355200/819591218303991808/1306350877346500702

**Comment by trav5555** [comment] 2024-11-14 19:40
I reported it as https://gitlab.com/OpenMW/openmw/-/issues/8231

**Comment by trav5555** [comment] 2024-11-18 15:40
Fixed on OpenMW side with https://gitlab.com/OpenMW/openmw/-/commit/4a911a647df944ef0926225a9722d058368c20f2, so I suppose this ticket can be closed?

We'll just have to recommend downloading a 0.49 OpenMW version from 2024-11-18 (maybe 19th for good measure), i.e. a package from **Development Builds** at https://openmw.org/downloads/

**Comment by Assumeru** [comment] 2024-11-18 15:54
Yeah. I've opened #755 for my earlier complaint about this mesh since it's not exactly unique to this mesh.

**Closed by Assumeru** 2024-11-18 15:54 UTC
Labels: Compatibility
